#!/bin/bash

foamCleanTutorials

blockMesh | tee log.blockMesh

renumberMesh -overwrite

surfaceFeatures | tee log.surfaceFeatures

rm -rf 0
cp -r 0_org 0

decomposePar -copyZero 
mpirun -np 4 snappyHexMesh -overwrite | tee log.snappyHexMesh

rm -rf processor*

decomposePar

mpirun twoPhaseEulerFoam | tee log.slove

# twoPhaseEulerFoam | tee log.slove

#------------------------------------------------------------------------------
